# Generated by Django 2.2.2 on 2020-02-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0002_auto_20200218_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='asignacionColor',
            field=models.CharField(default='Blanco', max_length=30),
        ),
    ]
