# Generated by Django 2.2.2 on 2020-03-13 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0003_auto_20200218_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
