# Generated by Django 2.2.2 on 2020-02-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoMedico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('fecha_vencimiento', models.DateField(null=True)),
                ('fabricado_por', models.CharField(max_length=20)),
                ('registro_invima', models.CharField(max_length=20)),
                ('numero_lote', models.CharField(max_length=20)),
                ('presentacion_comercial', models.CharField(max_length=20)),
                ('forma_farmaceutica', models.CharField(max_length=20)),
                ('principio_activo', models.CharField(max_length=20)),
                ('unidad_medica', models.CharField(max_length=20)),
                ('porcentaje', models.CharField(max_length=20)),
                ('temperatura', models.CharField(max_length=20)),
                ('riesgo', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField()),
                ('codigo', models.IntegerField()),
                ('asignacionColor', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
